#!/usr/bin/env python3.10
""" Main module that starts 'weather' """
from pathlib import Path

from custom_exceptions import IpstackApiServiceError, OpenWeatherApiServiceError, CanNotWriteData
from history import JsonFileWeatherStorage, save_weather
from network import get_gps_coordinates, get_weather
from weather_formatter import openweather_api_formatter


def main():
    coordinates, weather = None, None
    try:
        coordinates = get_gps_coordinates()
    except IpstackApiServiceError:
        print("Something went wrong with ipstack.com")
        exit(1)
    try:
        weather = get_weather(coordinates)
    except OpenWeatherApiServiceError:
        print("Something went wrong openweather.org")
        exit(1)
    try:
        save_weather(weather,
                     JsonFileWeatherStorage(Path.cwd() / 'history.json')
                     )
    except CanNotWriteData:
        print("Can not save history")
    print(openweather_api_formatter(weather))


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print('Cancelled!!!')
        exit(1)
