#!/usr/bin/env python3.10
""" Main module that starts 'weather' """
from pathlib import Path
from custom_exceptions import IpstackApiServiceError, OpenWeatherApiServiceError
from network import get_gps_coordinates, get_weather
from weather_formatter import openweather_api_formatter
from history import PlainFileWeatherStorage, save_weather


def main():
    coordinates, weather = None, None
    try:
        coordinates = get_gps_coordinates()
    except IpstackApiServiceError:
        print("Something went wrong with ipstack.com")
        exit(1)
    try:
        weather = get_weather(coordinates)
    except OpenWeatherApiServiceError:
        print("Something went wrong openweather.org")
        exit(1)
    save_weather(weather,
                 PlainFileWeatherStorage(Path.cwd() / 'history.txt')
                 )
    print(openweather_api_formatter(weather))


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print('Cancelled!!!')
        exit(1)

# TODO: now on  45 page. Need to reach end of the book!
# TODO: add logger add mypy add flake8
